/**
 * List of Redux action types
 */
export const SEARCH_BUTTON_CLICKED = 'SEARCH_BUTTON_CLICKED';
export const SORT_BY_CLICKED = 'SORT_BY_CLICKED';
export const FETCH_BUSINESSES_BEGIN = 'FETCH_BUSINESSES_BEGIN';
export const FETCH_BUSINESSES_SUCCESS = 'FETCH_BUSINESSES_SUCCESS';
export const FETCH_BUSINESSES_FAILURE = 'FETCH_BUSINESSES_FAILURE';
export const SET_APP_LOCALE = 'SET_APP_LOCALE';
// End of file
